provider:
  name: coolify

resources:
  private_key:
    create:
      path: /security/keys
      method: POST
    read:
      path: /security/keys/{uuid}
      method: GET
    update:
      path: /security/keys/{uuid}
      method: PATCH
    delete:
      path: /security/keys/{uuid}
      method: DELETE

data_sources:
  private_keys:
    read:
      path: /security/keys
      method: GET
  private_key:
    read:
      path: /security/keys/{uuid}
      method: GET
