provider:
  name: coolify

resources:
  private_key:
    create:
      path: /security/keys
      method: POST
    read:
      path: /security/keys/{uuid}
      method: GET
    update:
      path: /security/keys/{uuid}
      method: PATCH
    delete:
      path: /security/keys/{uuid}
      method: DELETE
  server:
    create:
      path: /servers
      method: POST
    read:
      path: /servers/{uuid}
      method: GET
    update:
      path: /servers/{uuid}
      method: PATCH
    delete:
      path: /servers/{uuid}
      method: DELETE

data_sources:
  private_keys:
    read:
      path: /security/keys
      method: GET
  private_key:
    read:
      path: /security/keys/{uuid}
      method: GET
  teams:
    read:
      path: /teams
      method: GET
  team:
    read:
      path: /teams/{id}
      method: GET
  server:
    read:
      path: /servers/{uuid}
      method: GET
  # servers:
  #   read:
  #     path: /servers
  #     method: GET
